CREATE DATABASE IF NOT EXISTS forensic_db
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'app_password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE
ON forensic_db.*
TO 'app_user'@'%';

FLUSH PRIVILEGES;